### PR TITLE
Add showTree function with tests

### PR DESCRIPTION
**Pull request by harris-chris**
Hello - as discussed - I've added a `showTree` function that produces `tree`-command-like output.

### CODE REVIEW

**Review by jberryman — COMMENTED** [review]
Thanks! Since this adds a new dependency I think now it would make sense to create a new small package. Is that something you're interested in doing? If not, maybe we can put the colorize logic behind a cabal flag disabled by default

**Comment by harris-chris** [comment]
Hello - I'm not sure that the tree code merits its own package. How about
one of the following:
- I remove the colorizing
- we use a compiler flag like you say
- I hard-code the ANSI colour values in, rather than take them from the
external package
- I create a parallel `showTreeFormatted` function, which has two
additional parameters, each of type `String -> String`, by which users can
apply custom formatting to files and directories respectively?

**Comment by jberryman** [comment]
Any of those first four sounds like a good solutions to me. Thanks for being flexible!

**Comment by harris-chris** [comment]
Great - please see the new commit - it uses the last of the approaches I mentioned above.

**Comment by harris-chris** [comment]
Hello - any problems with this?

**Review by jberryman — APPROVED** [review]
Sorry for the delay, and thanks!

**Comment by harris-chris** [comment]
Great, thanks!

**Pull request merged**
